import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Board from "../components/ui/Board";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${inter.className} bg-background dark text-zinc-100 flex items-stretch`}
      >
        <div className="w-[50%]">
          <Board />
        </div>
        <div className="w-[50%] p-5">{children}</div>
      </body>
    </html>
  );
}
